name: montenegrin_latin_localization
description: A Flutter localization package specifically designed for Montenegrin Latin script (crnogorski/латиница) that provides comprehensive text translations and region-specific formatting.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter